### PR TITLE
Test for menu items

### PR DESCRIPTION
**Pull request by franktank**
WIP

### CODE REVIEW

**Comment by franktank** [comment]
grunt test

**Comment by franktank** [comment]
mocha modules/users/tests/server/order.server.model.tests.js 
mocha modules/users/tests/server/user.server.model.tests.js 
mocha modules/users/tests/server/user.server.routes.tests.js 
mocha modules/menu-items/tests/server/menu-item.server.model.tests.js 
mocha modules/menu-items/tests/server/menu-item.server.routes.tests.js

**Comment by ghost** [comment]
- Pulled down and tested the above listed cmds. Looks good.

**Comment by ghost** [comment]
- Tested the functionality of project via grunt 
- Checked all mocha test again, looks good 
- Ready to be merged

**Pull request merged**
